using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Module1.Migrations
{
    public partial class Addtesttable : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "RemittanceTransaction",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    ODConfimationId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    CustomerID = table.Column<int>(type: "int", nullable: true),
                    CustomerRefNo = table.Column<string>(type: "varchar(20)", unicode: false, maxLength: 20, nullable: true),
                    Source = table.Column<string>(type: "varchar(50)", unicode: false, maxLength: 50, nullable: true),
                    Amendment = table.Column<bool>(type: "bit", nullable: true),
                    RMTStatusID = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    RMTCCY = table.Column<string>(type: "varchar(5)", unicode: false, maxLength: 5, nullable: true),
                    EquivRMTCCY = table.Column<string>(type: "varchar(5)", unicode: false, maxLength: 5, nullable: true),
                    RMTAmount = table.Column<decimal>(type: "decimal(25,2)", nullable: true),
                    EquivRMTAmount = table.Column<decimal>(type: "decimal(25,2)", nullable: true),
                    ODDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    ODValueDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    ODFinalDueDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    ODCCY = table.Column<string>(type: "varchar(5)", unicode: false, maxLength: 5, nullable: true),
                    ODEquivCCY = table.Column<string>(type: "varchar(5)", unicode: false, maxLength: 5, nullable: true),
                    ODAmount = table.Column<decimal>(type: "decimal(25,2)", nullable: true),
                    ODEquivAmount = table.Column<decimal>(type: "decimal(25,2)", nullable: true),
                    ODOutstanding = table.Column<decimal>(type: "decimal(25,2)", nullable: true),
                    ReceiptDept = table.Column<string>(type: "varchar(10)", unicode: false, maxLength: 10, nullable: true),
                    SettlementDoc = table.Column<string>(type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ReferenceNo = table.Column<string>(type: "varchar(16)", unicode: false, maxLength: 16, nullable: true),
                    ReceptionNo = table.Column<string>(type: "varchar(16)", unicode: false, maxLength: 16, nullable: true),
                    GCMSRefNo = table.Column<string>(type: "varchar(16)", unicode: false, maxLength: 16, nullable: true),
                    ReceivingDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    RMTValueDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    POIssueingDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    POValueDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    BeneName = table.Column<string>(type: "nvarchar(70)", maxLength: 70, nullable: true),
                    BeneAddress = table.Column<string>(type: "nvarchar(70)", maxLength: 70, nullable: true),
                    BeneACCNo = table.Column<string>(type: "varchar(34)", unicode: false, maxLength: 34, nullable: true),
                    BeneBankName = table.Column<string>(type: "nvarchar(70)", maxLength: 70, nullable: true),
                    BeneBankAddress = table.Column<string>(type: "nvarchar(70)", maxLength: 70, nullable: true),
                    DebitACNo1 = table.Column<string>(type: "varchar(50)", unicode: false, maxLength: 50, nullable: true),
                    DebitACCurrency1 = table.Column<string>(type: "varchar(5)", unicode: false, maxLength: 5, nullable: true),
                    DebitACNo2 = table.Column<string>(type: "varchar(50)", unicode: false, maxLength: 50, nullable: true),
                    DebitACCurrency2 = table.Column<string>(type: "varchar(5)", unicode: false, maxLength: 5, nullable: true),
                    Custodian = table.Column<bool>(type: "bit", nullable: true),
                    BankCharges = table.Column<string>(type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    ChargeAccount = table.Column<string>(type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    DetailsOfPayment = table.Column<string>(type: "nvarchar(140)", maxLength: 140, nullable: true),
                    OtherInstruction = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                    EvidenceCheckByCBA = table.Column<string>(type: "varchar(200)", unicode: false, maxLength: 200, nullable: true),
                    CBAEvidenceCCY = table.Column<string>(type: "varchar(5)", unicode: false, maxLength: 5, nullable: true),
                    CBAEvidenceAmount = table.Column<decimal>(type: "decimal(25,2)", nullable: true),
                    CBADefferedCCY = table.Column<string>(type: "varchar(5)", unicode: false, maxLength: 5, nullable: true),
                    CBADefferedAmount = table.Column<decimal>(type: "decimal(25,2)", nullable: true),
                    OP1DefferedCCY = table.Column<string>(type: "varchar(5)", unicode: false, maxLength: 5, nullable: true),
                    OP1DefferedAmount = table.Column<decimal>(type: "decimal(25,2)", nullable: true),
                    FundConfirm = table.Column<bool>(type: "bit", nullable: true),
                    SendMT199ToBeneBank = table.Column<bool>(type: "bit", nullable: true),
                    ODFX = table.Column<bool>(type: "bit", nullable: true),
                    MultipleODFX = table.Column<bool>(type: "bit", nullable: true),
                    TRPart = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    CBAPart = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    MessageToOP = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                    ODRefNo = table.Column<string>(type: "varchar(12)", unicode: false, maxLength: 12, nullable: true),
                    PaymentMethod = table.Column<string>(type: "varchar(100)", unicode: false, maxLength: 100, nullable: true),
                    TaxPaymentMethod = table.Column<string>(type: "varchar(10)", unicode: false, maxLength: 10, nullable: true),
                    RegisterDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    LineNumber = table.Column<int>(type: "int", nullable: true),
                    TransactionType = table.Column<string>(type: "varchar(10)", unicode: false, maxLength: 10, nullable: true),
                    DebitTotalFlag = table.Column<bool>(type: "bit", nullable: true),
                    TaxPayment = table.Column<bool>(type: "bit", nullable: true),
                    ApplNo = table.Column<string>(type: "varchar(20)", unicode: false, maxLength: 20, nullable: true),
                    IntPaymentDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    IntPaymentInterval = table.Column<int>(type: "int", nullable: true),
                    IntPaymentIntervalType = table.Column<int>(type: "int", nullable: true),
                    IntPaymentNoOfDay = table.Column<int>(type: "int", nullable: true),
                    PrincipalRepayDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    PrincipalRepayInterval = table.Column<int>(type: "int", nullable: true),
                    PrincipalRepayIntervalType = table.Column<int>(type: "int", nullable: true),
                    PrincipalRepayNoOfDay = table.Column<int>(type: "int", nullable: true),
                    Remark = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ODTRCost = table.Column<decimal>(type: "decimal(9,6)", nullable: true),
                    RateFixingDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    ContractSpread = table.Column<decimal>(type: "decimal(9,6)", nullable: true),
                    CostType = table.Column<int>(type: "int", nullable: true),
                    InterestRateFinalRate = table.Column<decimal>(type: "decimal(9,6)", nullable: true),
                    FixFloat = table.Column<int>(type: "int", nullable: true),
                    InterestCcy = table.Column<string>(type: "nvarchar(4)", maxLength: 4, nullable: true),
                    InterestAmt = table.Column<decimal>(type: "decimal(20,3)", nullable: true),
                    InterestDays = table.Column<int>(type: "int", nullable: true),
                    CLNo = table.Column<string>(type: "varchar(7)", unicode: false, maxLength: 7, nullable: true),
                    TempoOutstanding = table.Column<decimal>(type: "decimal(25,2)", nullable: true),
                    TempoAvailBalance = table.Column<decimal>(type: "decimal(25,2)", nullable: true),
                    IsOverDue = table.Column<bool>(type: "bit", nullable: true),
                    PrintCount = table.Column<int>(type: "int", nullable: true),
                    PrintedBy = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    PrintedDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    InputtedBy = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    InputtedDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    ModifiedBy = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    ModifiedDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    GroupedBy = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    GroupedDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    AmendedBy = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    AmendedDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    AmendAckedBy = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    AmendAckedDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    SendAmendToOPBy = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    SendAmendToOPDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    AcknowledgedBy = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    AcknowledgedDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    ConfirmedBy = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    ConfirmedDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    ReturnedBy = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    ReturnedDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    DeletedBy = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    DeletedDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    RejectedBy = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    RejectedDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    ExportedDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    ExportedFileName = table.Column<string>(type: "varchar(255)", unicode: false, maxLength: 255, nullable: true),
                    ExportStatus = table.Column<int>(type: "int", nullable: true),
                    IsPrinted = table.Column<bool>(type: "bit", nullable: true),
                    Customer_Code = table.Column<string>(type: "varchar(50)", unicode: false, maxLength: 50, nullable: true),
                    CustomerName = table.Column<string>(type: "nvarchar(250)", maxLength: 250, nullable: true),
                    FixRMTAmount = table.Column<decimal>(type: "decimal(25,2)", nullable: true),
                    GroupReferenceNo = table.Column<string>(type: "varchar(16)", unicode: false, maxLength: 16, nullable: true),
                    GOTransNo = table.Column<string>(type: "varchar(6)", unicode: false, maxLength: 6, nullable: true),
                    GOGeneratingSession = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    GOTransStatusID = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    RMTAmount_AdjustByCBA = table.Column<decimal>(type: "decimal(25,2)", nullable: true),
                    TerminatedBy = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    TerminatedDate = table.Column<DateTime>(type: "datetime", nullable: true),
                    TenantId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
                    ExtraProperties = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ConcurrencyStamp = table.Column<string>(type: "nvarchar(40)", maxLength: 40, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_RemittanceTransaction", x => x.Id);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "RemittanceTransaction");
        }
    }
}
