// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Module1.EntityFrameworkCore;
using Volo.Abp.EntityFrameworkCore;

#nullable disable

namespace Module1.Migrations
{
    [DbContext(typeof(Module1DbContext))]
    partial class Module1DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.SqlServer)
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Module1.RemittanceTransactions.RemittanceTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AcknowledgedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AcknowledgedDate")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("AmendAckedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AmendAckedDate")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("AmendedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AmendedDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("Amendment")
                        .HasColumnType("bit");

                    b.Property<string>("ApplNo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("BankCharges")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("BeneACCNo")
                        .HasMaxLength(34)
                        .IsUnicode(false)
                        .HasColumnType("varchar(34)");

                    b.Property<string>("BeneAddress")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("BeneBankAddress")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("BeneBankName")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("BeneName")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<decimal?>("CBADefferedAmount")
                        .HasColumnType("decimal(25,2)");

                    b.Property<string>("CBADefferedCCY")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<decimal?>("CBAEvidenceAmount")
                        .HasColumnType("decimal(25,2)");

                    b.Property<string>("CBAEvidenceCCY")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("CBAPart")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CLNo")
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("ChargeAccount")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<Guid?>("ConfirmedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ConfirmedDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("ContractSpread")
                        .HasColumnType("decimal(9,6)");

                    b.Property<int?>("CostType")
                        .HasColumnType("int");

                    b.Property<bool?>("Custodian")
                        .HasColumnType("bit");

                    b.Property<int?>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("CustomerRefNo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Customer_Code")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DebitACCurrency1")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("DebitACCurrency2")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("DebitACNo1")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DebitACNo2")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("DebitTotalFlag")
                        .HasColumnType("bit");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("DetailsOfPayment")
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<decimal?>("EquivRMTAmount")
                        .HasColumnType("decimal(25,2)");

                    b.Property<string>("EquivRMTCCY")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("EvidenceCheckByCBA")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("ExportStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExportedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ExportedFileName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ExtraProperties")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ExtraProperties");

                    b.Property<int?>("FixFloat")
                        .HasColumnType("int");

                    b.Property<decimal?>("FixRMTAmount")
                        .HasColumnType("decimal(25,2)");

                    b.Property<bool?>("FundConfirm")
                        .HasColumnType("bit");

                    b.Property<string>("GCMSRefNo")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<Guid?>("GOGeneratingSession")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GOTransNo")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.Property<Guid?>("GOTransStatusID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GroupReferenceNo")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<Guid?>("GroupedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("GroupedDate")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("InputtedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("InputtedDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("IntPaymentDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("IntPaymentInterval")
                        .HasColumnType("int");

                    b.Property<int?>("IntPaymentIntervalType")
                        .HasColumnType("int");

                    b.Property<int?>("IntPaymentNoOfDay")
                        .HasColumnType("int");

                    b.Property<decimal?>("InterestAmt")
                        .HasColumnType("decimal(20,3)");

                    b.Property<string>("InterestCcy")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int?>("InterestDays")
                        .HasColumnType("int");

                    b.Property<decimal?>("InterestRateFinalRate")
                        .HasColumnType("decimal(9,6)");

                    b.Property<bool?>("IsOverDue")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPrinted")
                        .HasColumnType("bit");

                    b.Property<int?>("LineNumber")
                        .HasColumnType("int");

                    b.Property<string>("MessageToOP")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("MultipleODFX")
                        .HasColumnType("bit");

                    b.Property<decimal?>("ODAmount")
                        .HasColumnType("decimal(25,2)");

                    b.Property<string>("ODCCY")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<Guid?>("ODConfimationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ODDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("ODEquivAmount")
                        .HasColumnType("decimal(25,2)");

                    b.Property<string>("ODEquivCCY")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<bool?>("ODFX")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ODFinalDueDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("ODOutstanding")
                        .HasColumnType("decimal(25,2)");

                    b.Property<string>("ODRefNo")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<decimal?>("ODTRCost")
                        .HasColumnType("decimal(9,6)");

                    b.Property<DateTime?>("ODValueDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("OP1DefferedAmount")
                        .HasColumnType("decimal(25,2)");

                    b.Property<string>("OP1DefferedCCY")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("OtherInstruction")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("POIssueingDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("POValueDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("PrincipalRepayDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("PrincipalRepayInterval")
                        .HasColumnType("int");

                    b.Property<int?>("PrincipalRepayIntervalType")
                        .HasColumnType("int");

                    b.Property<int?>("PrincipalRepayNoOfDay")
                        .HasColumnType("int");

                    b.Property<int?>("PrintCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("PrintedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PrintedDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("RMTAmount")
                        .HasColumnType("decimal(25,2)");

                    b.Property<decimal?>("RMTAmount_AdjustByCBA")
                        .HasColumnType("decimal(25,2)");

                    b.Property<string>("RMTCCY")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<Guid?>("RMTStatusID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RMTValueDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("RateFixingDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ReceiptDept")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("ReceivingDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ReceptionNo")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime?>("RegisterDate")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("RejectedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RejectedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ReturnedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReturnedDate")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("SendAmendToOPBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("SendAmendToOPDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("SendMT199ToBeneBank")
                        .HasColumnType("bit");

                    b.Property<string>("SettlementDoc")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TRPart")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("TaxPayment")
                        .HasColumnType("bit");

                    b.Property<string>("TaxPaymentMethod")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("TempoAvailBalance")
                        .HasColumnType("decimal(25,2)");

                    b.Property<decimal?>("TempoOutstanding")
                        .HasColumnType("decimal(25,2)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TenantId");

                    b.Property<Guid?>("TerminatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("TerminatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("TransactionType")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("RemittanceTransaction", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
